### ISSUE TITLE
宜しければ記事一覧（post_list.html）ページにも各タイトル毎に「いいね」を実装する方法を教えていただけませんでしょうか？

### ISSUE THREAD

**Issue by ghost** [qlitre/django-iine-project#1]
お世話になっております。
また、突然のメッセージ大変申し訳ございません。連絡手段が見つからなかったのでこちらで失礼させて頂きます。
https://qlitre-weblog.com/django-iine-ajax-create/#hd0767d8049
上記の記事大変参考になりました。

宜しければ記事一覧（post_list.html）ページにも各タイトル毎に「いいね」を実装する方法も教えていただけませんでしょうか？

**Comment by qlitre** [comment]
投稿ありがとうございます。
ソースコードを更新しますので少々お待ちください。

**Comment by ghost** [comment]
お手数をお掛けして大変申し訳ございません。
Djangoについて勉強中ですので大変参考になります。
ありがとうございます。

**Comment by qlitre** [comment]
ポストリスト画面でのイイねの実装についてソースコードをpushしました。
やることとしては、詳細画面のコメントのイイねと同じです。

```python
# {'pk':{'count':ポストに対するイイネ数,'is_user_liked_for_post':bool},}という辞書を追加していく
        d = {}
        for post in self.object_list:
            # postに対するイイね数
            like_for_post_count = post.likeforpost_set.count()
            # ログイン中のユーザーがイイねしているかどうか
            is_user_liked_for_post = False
            if not self.request.user.is_anonymous:
                if post.likeforpost_set.filter(user=self.request.user).exists():
                    is_user_liked_for_post = True

            d[post.pk] = {'count': like_for_post_count, 'is_user_liked_for_post': is_user_liked_for_post}
```

ここの部分でcontextにポストごとのイイねの状況を持たせてテンプレートに渡します。
あとはテンプレート内で同様にイイねの表示、更新処理をします。

ついでにログイン、ログアウト機能をつけてみました。
ユーザーがログインしていないときにイイねボタンを押したときに、ログインページにリダイレクトさせるような処理を加えています。

**Comment by ghost** [comment]
大変参考になりました。
この度はご丁寧にありがとうございました。
早速学ばさせて頂きます！

**Comment by qlitre** [comment]
またご不明な点がございましたらお気軽にお問合せください。
Twitterでも構いません。
[@kuri_tter](https://twitter.com/kuri_tter)

こちらのIssueは一度Closeとさせていただきます。
